### ISSUE TITLE
Providing Jobson UI with the jobson installation

### ISSUE THREAD

**Issue by DannyBen** [adamkewley/jobson#103]
Is there any chance that the Jobson UI comes bundled and ready to run with the .deb installation?

If not, I saw there is a jobson ui docker, but could not find instructions on how to run it and connect it to the other two jobson servers.

Would love to see all of this more contained and have jobson serve spawn all three needed servers.

**Comment by adamkewley** [comment]
It isn't possible, no.

The UI is built entirely separately from the server, and the server can't handle encryption, which is always deferred to nginx/Apache (the assumption being that they will always be up-to-date with encryption libraries etc.)

The docker-based approach tries to resolve the "everything in one thing" problem by providing a single pre-integrated docker image, but other users have complained that they want separate images for each service (i.e. "proper" docker).

Which is to say, integration is always a PITA for stack projects, because everyone always wants a slightly different integration.

If I were to re-develop Jobson, I'd build it as a single-install (maybe even single-binary) deal with something like Rust and leave encryption/load-balancing as a "not my problem" deal in future.

**Comment by adamkewley** [comment]
(copypaste)

This is a great suggestion but, unfortunately, I don't personally have the time to implement new features for Jobson.

If someone else wants to pick it up, I'd be all ears, but it is likely that I (unfortunately) need to start advertising the project as either abandoned or looking for maintainers (because I can't currently ship patches)

**Comment by DannyBen** [comment]
Thanks. That's a shame, I really liked it. 
I will close my issues then.

Good luck.
