### ISSUE TITLE
feature request: callbacks on completion

### ISSUE THREAD

**Issue by niv** [adamkewley/jobson#107]
Suggestion:

Add callback struct to config.yml that can execute arbitrary shell scripts when a job completes, both on failure and success.

The events should receive the job directory at the very least, from which all needed data could be extracted. It should also run (synchronously) before the wds is cleaned up, if so configured.

Motivation for this request is add a global notify call to a third party event system. Right now, I have this in the shell script themselves (via exit trap), but having it in config.yml would cut down on some duplication.

Thank you for writing this fantastic piece of software. It is incredibly useful!

**Comment by adamkewley** [comment]
This is a great suggestion but, unfortunately, I don't *personally* have the time to implement new features for Jobson.

If someone else wants to pick it up, I'd be all ears, but it is likely that I (unfortunately) need to start advertising the project as either abandoned or looking for maintainers (because I can't currently ship patches)

**Comment by adamkewley** [comment]
Closing this,

Thanks for the input, but the project has has a `Jobson is effectively unmaintained` notice for 10 months now, and has had no further changes since then, so I am closing all issues and archiving the project until further notice.
