### ISSUE TITLE
Browse for files / paths? 

### ISSUE THREAD

**Issue by spooknik** [adamkewley/jobson#66]
Great piece of software I just stumbled upon. 

I'd like to make an interface for [video_transcoding](https://github.com/donmelton/video_transcoding) and the one missing piece of the puzzle seems to be choosing a file on the server. If there an interface option for this? I couldn't seem to find anything in the documentation (might be more poor searching)

Of course the path can always be manually input but it's nicer to have a file picker interface. 

Cheers!

**Comment by adamkewley** [comment]
Hi @spooknik .

There isn't currently a control for doing this, no :cry: . 

It's a great feature idea - although I probably do not have the time to implement it because I'm currently working on a bunch of incredibly unrelated projects (so I'd need to spin up on the Java/javascript again).

Just so I can scope the work, though, or if someone is reading this and wants to hop into the lovecraftian horror that is Jobson's sourcecode, a rough rundown of the work required is:

- Add a new `expectedInput` type, `server-side-file`, or add a new optional parameter to `file` that enables the spec-designer to specify a server-side directory from which to select a file
- Add relevant API additions (e.g. to the `/v1/specs/{spec}` endpoint) to give clients a (potentially, nested) list of files that are available on the server. This could be sent along with the `spec` definition or an extra sub-path (e.g. `/v1/specs/{spec}/{input}/files`?)
- Add configuration functions/variables for dereferencing the value at runtime (e.g. `args: [ "${expectedInputs.filePath}" ]`)
- Ensure all of this works, probably with some safety checks (e.g. the directory listing might need to have some maximum recusion allowance, allowed extensions, allowed permissions)
- Ensure that users *definitely* can't screw with the server by specifying a path that lies outside the spec-designer-specified tree (e.g. `../../../../../../etc/passwd`)
- Add support into the UI for showing the file listing directly in the UI with a relevant interface (e.g. a javascript tree view, or whatever). Users might expect to be able to refresh *just* the file listing because Jobson's typically used in back-of-house (read: hacky) deployments where it's forseeable that the user might be waiting for files to appear on the drive (e.g. because they ran something on some other software that writes an input file to a NAS somewhere else - I really wouldn't put this past people)
- (on top of this): add the usual backend testing, scalability testing, etc.

Out of (completely unrelated) interest @spooknik , what kind of size of deployment are you running? A previous request from a researcher ran into scalability problems on file uploads (Jobson's implementation of this is fairly bad) and the filesystem-based backend might have a rough time scaling to thousands of jobs (it was developed for a small team that would only occasionally run a job here or there). 

Knowing user's perf requirements is handy because--in some heavenly alternate universe--I would like to rewrite this whole thing in Rust/C++ with an SQLite backend. Unfortunately, I only get an hour here or there to maintain Jobson :(

**Comment by spooknik** [comment]
Wow, a huge reply in 15 minutes, thank you. 

Looking forward to seeing it a feature one day, totally understand about being busy. I'm just happy this project exists. 👍 

At the moment only planning on running one maybe 2 jobs at once. It's transcoding video and my target is to make really good quality encodes of blu-rays. So the fewer the jobs the better.

**Comment by adamkewley** [comment]
Closing this because it isn't under active development (although it was a great suggestion).

*If I manage to get the time/resources*, I'll skim the open+closed issues and create a feature issue based on this.
