### ISSUE TITLE
DOI for jobson

### ISSUE THREAD

**Issue by mtazzari** [adamkewley/jobson#80]
Hi Adam, Jobson is really a great tool and I am am using it to run the analysis for a publication.
I'd be happy to cite it to give a fair acknowledgement of its usage.
I couldn't find a DOI that I could use in my paper.
If jobson hasn't any yet, I kindly invite you to create one: on Zenodo it should take ~10-15 minutes.

Linking the repo to zenodo is pretty easy and straightforward. 
Zenodo is cool as it automatically creates new DOIs as new versions are released.
If I remember correctly a new DOI is created after the first release since the linking is done.
See instructions here: https://guides.github.com/activities/citable-code/

Cheers

**Comment by adamkewley** [comment]
Hi @mtazzari , I'm surprised you stuck with it this long! :heart: - it makes me happy to hear that people still find it useful!

I'll go sort out the Zenodo registration now and update the README + this issue accordingly

**Comment by mtazzari** [comment]
Oh yeah, jobson is incredibly smooth and stable, and once set up in a docker container, it just works, and works. 
Consider that I am still using version 0.1.0-beta3 because I didn't have time to update. I feared that perhaps some API has changed and I couldn't afford the time to debug how my code interacts with jobson. But I'll update to the latest release after the paper I am preparing is submitted. 

> I'll go sort out the Zenodo registration now and update the README + this issue accordingly

Fantastic!  Thank you so much!!
If it can be of any help, you can have a look at these two packages in which I do the Zenodo thing:
 - https://github.com/mtazzari/uvplot
 - https://github.com/mtazzari/galario

**Comment by adamkewley** [comment]
Great to hear :)

You should *hopefully* have a fairly straightforward upgrade after you upgrade to 1.0.0 or higher. The changes made since 1.0.0 should be non-breaking (at least, that's the intention). There may be some minor breaks between 0.1.0-beta3 and 1.0.0, though, because I may have thought "hm, I should break this now before it's frozen in for v1 deployments". I'd recommend backing up the deployment before trying an upgrade regardless though.

**Comment by adamkewley** [comment]
Other note: there's a delay in generating a DOI for this

I've registered it with Zenodo etc. but the way Zenodo works (using webhooks to automatically DOI each release) kind of assumes that a new release will be published after registering with Zenodo.

That would normally be fine--the release process is automated--but it turns out that Travis has been deprecated (a common theme in free CIs....) so although there's a new release waiting on `master` I really should *also* port the build over to GitHub Actions and make sure the release process is alright on that; otherwise, I'll have to release manually-built binaries of the latest release - something I don't really want to do, because it's harder to trace down.

If I can't get the GitHub action working, I'll try and manually publish a DOI for an existing (automated) Jobson release, so you at least have *something* to cite.

**Comment by adamkewley** [comment]
@mtazzari , just as a hold-over while I handle the GitHub action (which might end up taking a bunch of time because I may be called away to do something else, etc.), I manually created a DOI for v1.0.11:

https://doi.org/10.5281/zenodo.5148300

**Comment by mtazzari** [comment]
That's amazing, thank you very much Adam!

I was also hit by the Travis change towards open source project if that is
what you mean.
I found that when i had to update my uvplot package and all at once, just
to make a new release, I had to migrate all my CI to guthub actions! It
took a few hours but github actions works perfectly, and is super fast.
This is the issue where i addressed it, in case it might help:
https://github.com/mtazzari/uvplot/issues/44



—
Dr. Marco Tazzari - ***@***.*** -
https://www.ast.cam.ac.uk/people/marco.tazzari
Postdoctoral Research Associate - office H32  phone +44 (0)1223 766691
Institute of Astronomy, University of Cambridge, Madingley Road, Cambridge,
CB3 0HA, UK

**Comment by adamkewley** [comment]
I just published 1.0.12 with GitHub actions - although it seems to have problems with building + deploying the docker container (need to investigate this). The Zenodo hook seems to automatically publish each release with a DOI:

**Comment by adamkewley** [comment]
I'll close this for now, because you have the manual DOI for 1.0.11 and the hooks are setup to produce somewhat-passable DOIs for future releases. Thanks again for bringing this up @mtazzari !

I'll try and add a DOI badge into the main homepage as well, and I need to remove any remnants of travis etc. when I get some time
