### ISSUE TITLE
Feature request: able to show an image on a job submission page.

### ISSUE THREAD

**Issue by herofmm** [adamkewley/jobson#83]
Dear Adam,

First, thank you for making this wonderful project and share it freely.  We are currently developing a website using this tool, and I would like to request a feature addition as follow.

Would it be possible to show an image on the job submission page.  Currently, we can add texts.  But, it will be always better to show a diagram or an image for the target problem.

Thank you.
Donghyuk Shin

p.s. below is our deployed website for chemical kinetics calculation.
https://flame.kaist.ac.kr

**Comment by adamkewley** [comment]
Hi @herofmm 

I'm very happy that you have used it in chemistry! I used to study chemistry in a past life :D

Adding that feature shouldn't be *too* hard. It will likely require adding an `headerImage:` field into `spec.yml`, followed by adding a `"headerImage": { "filename": "file.png", "data": "base64str" }` field onto the JSON that base64-encodes the image somehow.

However, I can't commit to doing it right away. I'm currently juggling several large projects and don't really have time to focus on Jobson so often. I'll try and hammer it out one evening/weekend but, again, I can't say "yep, it will be done by next week" because many work/life commitments pop up recently. 

If anyone else reading this wants to give it a whirl, then be my guest. Implementation steps will be:

- Add `headerImage` field into the `spec.yml`
- Whenever someone requests a spec via the API:
  - Do the usual steps (validation, converting into JSON)
  - Try to load the image (cached?) from the specified `headerImage` path server-side
  - If loading fails, print a one-time warning/error to the server logs, maybe have an `error` field client side?
  - If loading succeeds, convert the content bytes into base64 and send it to the client
- Client side, in the `spec` UI, have it ask whether the response contains a `headerImage` field. If it does, have the UI unpack the base64 into an `Image` and place the image in the webpage DOM so that it's visible. Maybe apply some basic CSS to ensure the image is percentage scaled on smaller devices (e.g. mobiles)

**Comment by tartics** [comment]
Dear @adamkewley 

First, thank you for the great project!
I'm one of the people who developing a website for chemical kinetics calculation.

I'm trying to put the image on the job summation page in the way you said it.
I added `headerImage:` into `spec.yml` and put `"headerImage": { "filename": "file.png", "data": "base64str" }` in `share/java/jobson-swagger.json` file. However, it didn't work.

So, I wonder if `jobson-swagger.json` is JSON.
If right, where I have to put `"headerImage":`?

Thanks a lot.

**Comment by adamkewley** [comment]
The `headerImage` field is not yet implemented in `jobson`, so this will
not work yet. I need to spend some time--which I don't currently have very
much of--to implement the feature for you!

Adam

**Comment by adamkewley** [comment]
Closed because, although it's a great feature idea, there is no active development time to implement this (I'm working on several other projects)
