### ISSUE TITLE
Jobson API Error

### ISSUE THREAD

**Issue by threehappypenguins** [adamkewley/jobson#85]
I haven't used Jobson for a couple a weeks and when I went to open the UI today, it says "There was an error loading jobs from the Jobson API. The API's error message was: Error." or "There was an error loading job specs from the Jobson API. The API's error message was: Error."

It doesn't ask me for my username and password. Just presents with those screens, depending on whether I'm in Jobs or Submit Job.

**Comment by threehappypenguins** [comment]
Never mind. Not sure how to delete this. Jobson was not running, that's why. I forgot that I had a power outage the other day and had to shut the server down, and didn't restart the Jobson service with my bash script. Oops. Sorry I feel dumb now. Lol

**Comment by threehappypenguins** [comment]
Jobson wasn't running. Now it is. Problem solved.

**Comment by adamkewley** [comment]
Ah, sorry to hear this :(

No need to apologize: it's a UX problem that the UI should handle better. Rather than saying just "error", it would ideally read through the response error object in JavaScript to give you something more useful (depending on how your reverse proxy responds).

If I had enough time to rewrite Jobson, id probably ship it with the UI already integrated into the server to stop oddities like this happening as easily: even I get caught out by it sometimes :)
