### ISSUE TITLE
mvn -B verify clean fails

### ISSUE THREAD

**Issue by frafra** [adamkewley/jobson#99]
I run `mvn -B verify clean -X` to try to build the Java package, but it looks like it tries to fetch a dependency, and it fails.
Could it be that the latest release (1.0.13) has not been fully released? There is no GitHub release associated to that tag, for example.

```
#16 25.69 [ERROR] Failed to execute goal on project jobson-swagger: Could not resolve dependencies for project com.github.jobson:jobson-swagger:pom:1.0.13: Could not find artifact com.github.jobson:jobson:jar:1.0.13 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

Using `mvn -B package -P release` is able to build `jobson-swagger`.

**Comment by adamkewley** [comment]
Jobson isn't published to maven central because it's unsuitable for it. Jobson is built as a multi-language platform that only exposes basic textual APIs to users (config files, CLI, HTTP APIs), so the most suitable platform for delivering it is as an OS-level installer, an OS-level package, or something like a Docker container.

There is an academic argument for deploying to central--i.e. that it's *just* a binary repository that *happens* to mostly host `jar` libraries and it *could* be used to host fat executables--but I actively avoided doing so because it seems like a fairly niche use-case to grab jobson via (e.g.) nexus/artifactory.

**Comment by adamkewley** [comment]
Closing because the issue--as far as I understand--is that `jobson` isn't on maven central. It shouldn't be - it's a platform that happens to use java and could, in principle, be entirely rewritten in Rust/C++ without breaking user-facing APIs (which are all langyuage-agnostic, save for a little authentication plugin feature that was used by Gaia, but isn't documented publically)
